Noh doc postprocessing sw
ices-eg/wg_WGFAST pull request #33
Opened 2020-03-16 17:59 UTC by nilsolav

Added a chapter on the use of the convention for typical post processing steps.

2020-03-17 04:37 UTC, gavinmacaulay requested changes
This commit changes every line in the document. Perhaps the line endings changed? Please adjust the commit so that we can see what lines actually changed.

2020-03-17 04:40 UTC, gavinmacaulay commented on SONAR-netCDF4/docs/crr341.adoc
> +There are several processing steps that are common among the different postprocessing tools used by the community, and there is a growing need to use the different tools interchangeably. This chapter
```suggestion
There are several processing steps that are common among the different postprocessing tools used by the community, and there is a growing need to use the different tools interchangeably. This chapter describes a few standard processing steps and outlines how the standard is intended to be used to facilitate this interchangeability. Note that the steps may be different between tools, and that the convention only recommends how to store the data for the steps that are most common. We do not address how and in which order to process your data.
```

2020-03-17 04:41 UTC, gavinmacaulay commented on SONAR-netCDF4/docs/crr341.adoc
> +Exchange of information between different parts in the processing chain is becoming increasingly important. This is particularly relevant for emerging deep learning and machine learning frameworks, t
```suggestion
Exchange of information between different parts in the processing chain is becoming increasingly important. This is particularly relevant for emerging deep learning and machine learning frameworks, that have hardware requirements that are often different to the computers that are used for traditional desktop applications. Processing tools that run on autonomous platforms are also a need, which often require a different suite of software solutions, typically tailored to low power situations. 
```

2020-03-17 04:45 UTC, gavinmacaulay commented on SONAR-netCDF4/docs/crr341.adoc
> +Figure 1. Typical steps in a postprocessing chaing for acoustical water column data. (TODO: Link these boxes to the groups in the convention and check if there are other needs)
```suggestion
.Typical steps in a postprocessing chain for acoustical water column data. (TODO: Link these boxes to the groups in the convention and check if there are other needs)
[[postprocessing_data_flow_figure]]
image::postprocessingDataFlowFigure.svg[align="center"]

```

2020-03-17 04:47 UTC, gavinmacaulay commented on SONAR-netCDF4/docs/crr341.adoc
> +Typical steps in the postprocessing chain of marine sonar data consist of preprocessing and noise removal, bottom detection, classification, and integration (Figure 1). Here we outline the different
```suggestion
Typical steps in the postprocessing chain of marine sonar data consist of preprocessing and noise removal, bottom detection, classification, and integration (<<postprocessing_data_flow_figure>>). Here we outline the different groups in the convention that can support the input and output from these steps. If a processing software step can read the data, process the information and write back to the data using the convention, other software can pick it up and process it further. 
```

2020-03-17 04:49 UTC, gavinmacaulay commented on SONAR-netCDF4/docs/crr341.adoc
> +There are several processing steps that are common among the different postprocessing tools used by the community, and there is a growing need to use the different tools interchangeably. This chapter
```suggestion
There are several processing steps that are common among the different postprocessing tools used by the community, and there is a growing need to use the different tools interchangeably. This chapter describes a few standard processing steps and outlines how the convention is intended to be used to facilitate the interchangeability. Note that the steps may be different between tools, and the convention only recommends how to store the data for the steps that are most common. We do not address how and in which order to process your data.
```

2020-03-18 08:19 UTC, gavinmacaulay approved these changes

2020-03-18 08:25 UTC, gavinmacaulay commented
Looks fine. Some polishing probably needed, but this can happen in prep for a new release of the convention.

2020-03-18 10:48 UTC, nilsolav commented
Yes, let's do the language editing later. What is missing is the link to the groups later in the document.

2020-03-18 18:37 UTC, merged